import type { Testimonial, TestimonialSummary } from "@/types/testimonial";

export const testimonialSummary: TestimonialSummary = {
  rating: 4.8,
  totalReviews: 361,

  ratings: [
    {
      stars: 5,
      percentage: 83,
    },
    {
      stars: 4,
      percentage: 7,
    },
    {
      stars: 3,
      percentage: 3,
    },
    {
      stars: 2,
      percentage: 0,
    },
    {
      stars: 1,
      percentage: 7,
    },
  ],

  satisfaction: [
    {
      label: "User Satisfaction",
      value: 93,
    },
    {
      label: "Response",
      value: 92,
    },
    {
      label: "Quality",
      value: 91,
    },
    {
      label: "Delivery",
      value: 103,
    },
  ],
};

export const testimonials: Testimonial[] = [
  {
    id: "bryan-malaa",
    name: "Bryan Malaa",
    location: "Philippines",
    rating: 5,
    date: "29-August-2026",
    product: "Estradiol Valerate Injection",
  },

  {
    id: "frank-rendon",
    name: "Frank Rendon",
    location: "United States Of America",
    rating: 5,
    date: "14-September-2026",
    product: "Testosterone Enanthate Injection",
  },

  {
    id: "tanya-hammond",
    name: "Tanya Hammond",
    location: "Australia",
    rating: 5,
    date: "03-September-2026",
    product: "Insulin Injection",
  },

  {
    id: "jonas",
    name: "Jonas",
    location: "United States Of America",
    rating: 5,
    date: "12-August-2026",
    product: "Lemborexant Tablets",
    review:
      "Amazing. Would leave 6 stars if I could. Great seller, great packaging. No spam calls or messages. Calm and helpful",
  },

  {
    id: "steve-lothian",
    name: "Steve Lothian",
    location: "Australia",
    rating: 5,
    date: "19-June-2026",
    product: "Cyclobenzaprine Hydrochloride",
    review: "Fast service thank you.",
  },

  {
    id: "edward",
    name: "Edward",
    location: "United States Of America",
    rating: 5,
    date: "19-May-2026",
    product: "Albendazole Tablets",
    review: "Great ordering assistance!",
  },

  {
    id: "vickie-e",
    name: "Vickie E",
    location: "United States Of America",
    rating: 5,
    date: "24-April-2026",
    product: "Budesonide Inhaler & Nebulizer",
    review: "Perfect!",
  },

  {
    id: "rh",
    name: "RH",
    location: "United States Of America",
    rating: 5,
    date: "17-April-2026",
    product: "Testosterone Enanthate Injection",
    review: "Received exactly what I requested plus GIFT!",
  },

  {
    id: "sven-teichmann",
    name: "Sven Teichmann",
    location: "Australia",
    rating: 5,
    date: "14-February-2026",
    product: "Zopiclone Tablets",
    review:
      "Another order safely received. Trusted supplier providing genuine products. Thank you very much",
  },

  {
    id: "philip-skingsley",
    name: "Philip Skingsley",
    location: "Thailand",
    rating: 5,
    date: "08-February-2026",
    product: "Lignocaine Hydrochloride Gel",
    review:
      "Great service and contact to make sure the delivery went smoothly.",
  },

  {
    id: "pepe",
    name: "Pepe",
    location: "Spain",
    rating: 5,
    date: "21-January-2026",
    review: "Everything was perfect. Very fast shipping. Highly recommended.",
  },

  {
    id: "dani",
    name: "Dani",
    location: "Switzerland",
    rating: 5,
    date: "14-November-2025",
    product: "Kamagra Tablets",
    review: "everything perfect",
  },

  {
    id: "babu-lal",
    name: "Babu Lal",
    location: "Varanasi, Uttar Pradesh",
    rating: 5,
    date: "29-September-2025",
    product: "Tadaday 40 mg Tablet",
    review: "Great experience",
  },

  {
    id: "edward-stanioski",
    name: "Edward Stanioski",
    location: "United States Of America",
    rating: 5,
    date: "05-August-2026",
    product: "Nandrolone Injection",
  },

  {
    id: "jerry-nogot",
    name: "Jerry Nogot",
    location: "Philippines",
    rating: 5,
    date: "29-July-2026",
    product: "Cabazitaxel Injection",
  },

  {
    id: "ahmed-soa",
    name: "Ahmed SoA",
    location: "Sweden",
    rating: 5,
    date: "24-July-2026",
    product: "Levothyroxine Sodium Tablet",
  },

  {
    id: "james",
    name: "James",
    location: "Australia",
    rating: 5,
    date: "24-July-2026",
    product: "Flecainide Tablet",
  },

  {
    id: "dave",
    name: "Dave",
    location: "United Kingdom",
    rating: 5,
    date: "03-July-2026",
    product: "Medicine Drop Shippers",
  },

  {
    id: "carson-best",
    name: "Carson Best",
    location: "United States Of America",
    rating: 5,
    date: "30-June-2026",
  },

  {
    id: "gilbert-turner",
    name: "Gilbert Turner",
    location: "United States Of America",
    rating: 5,
    date: "16-June-2026",
    product: "Testosterone Enanthate Injection",
  },
  {
    id: "jonas-weiss",
    name: "Jonas Weiss",
    location: "Switzerland",
    rating: 5,
    date: "30-May-2026",
    product: "Tretinoin Cream",
    review: "Everything went smoothly",
  },
  {
    id: "beulah-dahlin",
    name: "Beulah Dahlin",
    location: "United States Of America",
    rating: 5,
    date: "01-May-2026",
    product: "Careprost Eye Drops",
    attributes: ["Response"],
  },
  {
    id: "jeff-australia",
    name: "Jeff",
    location: "Australia",
    rating: 5,
    date: "19-March-2026",
    attributes: ["Response", "Quality", "Delivery"],
  },
  {
    id: "jonah-germany",
    name: "Jonah",
    location: "Germany",
    rating: 5,
    date: "19-February-2026",
    product: "Cenforce Tablets",
    attributes: ["Response", "Delivery"],
  },
  {
    id: "francisco-godoy",
    name: "Francisco Godoy",
    location: "Chile",
    rating: 5,
    date: "03-February-2026",
    product: "Careprost Eye Drops",
    attributes: ["Response", "Quality"],
  },
  {
    id: "rahul-ajmer",
    name: "Rahul",
    location: "Ajmer, Rajasthan",
    rating: 5,
    date: "27-December-2025",
    product: "Cenforce D Tablets",
    attributes: ["Response", "Quality", "Delivery"],
  },
  {
    id: "prateek-kadam",
    name: "Prateek Kadam",
    location: "Pune, Maharashtra",
    rating: 5,
    date: "03-December-2025",
    product: "Ropark 0.25mg Ropinirole Tablet",
    attributes: ["Response"],
  },
  {
    id: "sonny-garcia",
    name: "Sonny Garcia",
    location: "United States Of America",
    rating: 5,
    date: "09-November-2025",
    product: "Sirolimus Tablets",
    attributes: ["Response", "Quality", "Delivery"],
  },
  {
    id: "john-finch",
    name: "John Finch",
    location: "Thailand",
    rating: 5,
    date: "07-November-2025",
    product: "Tenofovir Tablet",
    attributes: ["Response"],
  },
  {
    id: "mohammed-yahyaoui",
    name: "Mohammed Yahyaoui",
    location: "France",
    rating: 5,
    date: "12-October-2025",
    product: "Prucalopride Tablet",
    attributes: ["Response"],
  },
  {
    id: "michelle-knight",
    name: "Michelle Knight",
    location: "United Kingdom",
    rating: 5,
    date: "28-August-2026",
    product: "Ivermectin Tablets",
  },
  {
    id: "james-bryan",
    name: "James.Bryan",
    location: "United States Of America",
    rating: 5,
    date: "20-August-2026",
    product: "Sildenafil Tablets",
  },
  {
    id: "wyatt-jenkinson",
    name: "Wyatt Jenkinson",
    location: "United States Of America",
    rating: 5,
    date: "26-July-2026",
    product: "Hair Loss Medicines",
  },
  {
    id: "roy-usa",
    name: "Roy",
    location: "United States Of America",
    rating: 5,
    date: "23-July-2026",
    product: "Artesunate Tablet",
  },
  {
    id: "chandan-sahoo",
    name: "Chandan Sahoo",
    location: "Keonjhar, Odisha",
    rating: 5,
    date: "16-July-2026",
    product: "Neostigmine 15mg tablet",
  },
  {
    id: "pedro-vergara",
    name: "PEDRO VERGARA",
    location: "Chile",
    rating: 5,
    date: "05-July-2026",
    product: "Imatinib Tablet",
  },
  {
    id: "alcides-sanchez",
    name: "Alcides Sanchez",
    location: "United States Of America",
    rating: 5,
    date: "26-June-2026",
    product: "Online Pharmacy",
  },
  {
    id: "emam-sk",
    name: "Emam Sk",
    location: "Bankura, West Bengal",
    rating: 5,
    date: "24-June-2026",
    product: "Dithranol Ointment",
  },
  {
    id: "shane-usa",
    name: "Shane",
    location: "United States Of America",
    rating: 5,
    date: "22-June-2026",
    product: "Dorzolamide Ophthalmic Eye Drops",
  },
  {
    id: "jdan-king",
    name: "Jdan King",
    location: "United States Of America",
    rating: 5,
    date: "11-June-2026",
  },
  {
    id: "charles-carpenter",
    name: "Charles Carpenter",
    location: "United States Of America",
    rating: 5,
    date: "22-April-2026",
  },
  {
    id: "victor-rodriguez",
    name: "Victor Rodriguez",
    location: "United States Of America",
    rating: 5,
    date: "10-April-2026",
    product: "Hormone Tablet",
  },
  {
    id: "allen-king-phd",
    name: "Allen King PhD",
    location: "United States Of America",
    rating: 5,
    date: "23-March-2026",
    product: "ROSUFREE 5 MG",
  },
  {
    id: "chris-peters",
    name: "Chris Peters",
    location: "United States Of America",
    rating: 5,
    date: "17-March-2026",
    product: "Indometacin Capsules",
  },
  {
    id: "ralph-lascola",
    name: "Ralph Lascola",
    location: "United States Of America",
    rating: 5,
    date: "09-March-2026",
    product: "Steroid",
  },
  {
    id: "edgar-enriquez",
    name: "Edgar Enriquez",
    location: "Mexico",
    rating: 5,
    date: "25-January-2026",
    product: "Minoxidil Tablet",
  },
  {
    id: "sonja-usa",
    name: "Sonja",
    location: "United States Of America",
    rating: 5,
    date: "24-January-2026",
    product: "Vitamin C injection",
  },
  {
    id: "lahcen-lasfar",
    name: "Lahcen Lasfar",
    location: "Morocco",
    rating: 5,
    date: "11-January-2026",
    product: "Tofacitinib Tablets",
  },
  {
    id: "diju-debbarma",
    name: "Diju Debbarma",
    location: "Hyderabad, Telangana",
    rating: 5,
    date: "11-January-2026",
    product: "Trenbolone Acetate Injection (10ml)",
  },
  {
    id: "robert-mackenzie",
    name: "Robert Mackenzie",
    location: "Australia",
    rating: 5,
    date: "09-January-2026",
    product: "Online Pharmacy",
  },
  {
    id: "bodyesthetics",
    name: "BodyEsthetics",
    location: "United States Of America",
    rating: 5,
    date: "04-December-2025",
    product: "Glutathione Injection",
  },
  {
    id: "jose-luis",
    name: "Jose Luis",
    location: "Mexico",
    rating: 5,
    date: "26-November-2025",
  },
  {
    id: "dinesh-patel",
    name: "Dinesh Patel",
    location: "United States Of America",
    rating: 5,
    date: "19-November-2025",
    product: "Duralast 30 Tablet",
  },
  {
    id: "john-holmes",
    name: "John Holmes",
    location: "United States Of America",
    rating: 5,
    date: "10-November-2025",
  },
  {
    id: "yesi",
    name: "Yesi",
    location: "Mexico",
    rating: 5,
    date: "07-November-2025",
    product: "Insulin Injection",
  },
  {
    id: "arthur-coquet",
    name: "Arthur Coquet",
    location: "France",
    rating: 5,
    date: "27-October-2025",
  },
  {
    id: "james-royle",
    name: "James Royle",
    location: "United Kingdom",
    rating: 5,
    date: "21-October-2025",
    product: "Ivermectin Cream",
  },
  {
    id: "afranio-ramos",
    name: "Afranio Ramos",
    location: "United States Of America",
    rating: 5,
    date: "07-October-2025",
    product: "Sildenafil Oral Jelly",
  },
  {
    id: "aonza",
    name: "Aonza",
    location: "Thailand",
    rating: 5,
    date: "03-October-2025",
    product: "Cytomel Tablets",
  },
  {
    id: "matt-canada",
    name: "Matt",
    location: "Canada",
    rating: 5,
    date: "31-July-2025",
    product: "Benfotiamine Tablet & Capsules",
    review: "Very knowledgeable and professional seller.",
    attributes: ["Response", "Quality", "Delivery"],
  },
  {
    id: "sondra-barnett",
    name: "Sondra Barnett",
    location: "United States Of America",
    rating: 5,
    date: "24-July-2025",
    product: "Foracort Inhaler",
    review:
      "Very kind customer service. Medications are amazing. Shippping time is outstanding my rep is on top of things. Very happy about products and especially prices",
    attributes: ["Response", "Quality", "Delivery"],
  },
  {
    id: "mat-australia",
    name: "Mat",
    location: "Australia",
    rating: 5,
    date: "01-July-2025",
    product: "Pregabalin Capsules & Tablets",
    review:
      "The staff seem really helpful and not pushing medication onto me but rather letting me know that there here to help if I reach out. I will give a full review after my final experience with working with Shree Shyam International. Looking forward to it…",
    attributes: ["Response"],
  },
  {
    id: "jessica-usa",
    name: "Jessica",
    location: "United States Of America",
    rating: 5,
    date: "18-June-2025",
    product: "Insulin Injection",
    review:
      "So I’m a USA buyer. I am relieved to find a great and honest seller. They shipped the product I needed and provided tracking. Also, they answered all my questions. Thank you .",
    attributes: ["Response", "Quality", "Delivery"],
  },
  {
    id: "caglar-gursoy",
    name: "Caglar Gursoy",
    location: "Turkey",
    rating: 5,
    date: "13-June-2025",
    product: "Cariprazine Capsule",
    review: "Really responsive, great service and prices.",
    attributes: ["Response", "Quality", "Delivery"],
  },
  {
    id: "indiamart-buyer-greece",
    name: "IndiaMART Buyer",
    location: "Greece",
    rating: 5,
    date: "07-June-2025",
    product: "Tenvir Tablets",
    review: "Everything was perfect.. packaging included :-) Fast Shipping !!",
    attributes: ["Response", "Quality", "Delivery"],
  },
  {
    id: "westly-williams",
    name: "Westly Williams",
    location: "United States Of America",
    rating: 5,
    date: "30-May-2025",
    review:
      "Shipment arrived 2 days ahead of schedule. Very very pleased with the service and support given. Will be back.",
    attributes: ["Response", "Quality", "Delivery"],
  },
  {
    id: "hugh-diffly",
    name: "Hugh Diffly",
    location: "United States Of America",
    rating: 5,
    date: "08-May-2025",
    review:
      "Very impressive. Quick delivery and immediate responses from the company, before and after purchase.",
    attributes: ["Response", "Quality", "Delivery"],
  },
  {
    id: "eddie-jones",
    name: "Eddie Jones",
    location: "United States Of America",
    rating: 5,
    date: "28-April-2025",
    review:
      "Everyone was so polite and didn't hesitate to help me with my requirements",
    attributes: ["Response", "Quality", "Delivery"],
  },
  {
    id: "cvm",
    name: "CVM",
    location: "United States Of America",
    rating: 5,
    date: "06-January-2025",
    product: "Drop Shipping Services",
    review: "⭐️⭐️⭐️⭐️⭐️ 10/10 Very Satisfied",
    attributes: ["Quality", "Delivery"],
  },
  {
    id: "douglas-j-norris",
    name: "Douglas J NORRIS",
    location: "Australia",
    rating: 5,
    date: "19-December-2024",
    product: "Semaglutide Tablets",
    review:
      "Great to deal with and no problem sending goods to BNE Australia. Highly recommend.",
    attributes: ["Response", "Quality", "Delivery"],
  },
  {
    id: "russ-usa",
    name: "Russ",
    location: "United States Of America",
    rating: 5,
    date: "03-December-2024",
    product: "Fenbendazole Tablet",
    review: "Very helpful and courteous.",
    attributes: ["Response", "Quality"],
  },
  {
    id: "traves-patterson",
    name: "Traves Patterson",
    location: "United States Of America",
    rating: 5,
    date: "28-November-2024",
    product: "Cenforce 200 Mg Tablets",
    review: "I got another new order sir",
    attributes: ["Response", "Quality", "Delivery"],
  },
  {
    id: "michael-uk",
    name: "Michael",
    location: "United Kingdom",
    rating: 5,
    date: "25-November-2024",
    product: "Fenbendazole Tablet",
    review:
      "Fantastic service. Was told 2 weeks but arrived in 1 week. Very polite. Easy transaction. I would and have used again. Thank you so very much, Iam very pleased.",
    attributes: ["Response", "Quality", "Delivery"],
  },
  {
    id: "danny-wachter",
    name: "Danny Wachter",
    location: "United States Of America",
    rating: 5,
    date: "23-November-2024",
    product: "Carisoprodol Tablets",
    review: "Quick reminder",
    attributes: ["Response"],
  },
  {
    id: "pretty-oeme",
    name: "Pretty Oeme",
    location: "United States Of America",
    rating: 5,
    date: "18-October-2024",
    product: "Ozempic Semaglutide Injection",
    review: "Good Product",
    attributes: ["Response", "Quality", "Delivery"],
  },
  {
    id: "tim-cole",
    name: "Tim Cole",
    location: "Australia",
    rating: 5,
    date: "17-October-2024",
    review:
      "great price and did a great job getting product delivered to Australia.Quality Seller.",
    attributes: ["Response", "Quality", "Delivery"],
  },
  {
    id: "johns-appliance-repair-service",
    name: "Johns Appliance Repair Service",
    location: "Australia",
    rating: 5,
    date: "03-October-2024",
    product: "Steroid Hormones",
    review: "punctality",
    attributes: ["Response", "Quality", "Delivery"],
  },
  {
    id: "roald-moy",
    name: "Roald Moy",
    location: "Philippines",
    rating: 5,
    date: "14-September-2024",
    product: "Ivermectin Tablets",
    review:
      "They were quick to accommodating my inquiry. But I decided to get from another supplier.",
    attributes: ["Response"],
  },
  {
    id: "robin-usa",
    name: "Robin",
    location: "United States Of America",
    rating: 5,
    date: "01-September-2024",
    product: "Hydroxychloroquine Sulfate Tablet",
    review: "First time I ordered from this company. Will do so again.",
    attributes: ["Response", "Quality", "Delivery"],
  },
  {
    id: "matthew-schnupp",
    name: "Matthew Schnupp",
    location: "United States Of America",
    rating: 5,
    date: "27-August-2024",
    product: "Levothyroxine Sodium Tablet",
    review: "Shree was communicative and helpful.",
  },
];

testimonials.sort(
  (first, second) =>
    (second.review?.length ?? 0) - (first.review?.length ?? 0),
);
